Feature/243 calculate sponsored percentage
BesLogic/releaf-canopeum pull request #255
Opened 2024-09-30 16:35 UTC by NicolasDontigny

Implemented the calculations for the sponsored progress of a site.

I had to update models, serializers, and so I squashed the migrations to one initial script again.
Sponsor progress is now calculated dynamically according to the number of species of a site and of its batches, it is not a field that should be stored in the model/DB

2024-10-01 18:13 UTC, Samuel-Therrien-Beslogic commented
Remember to link your PR and issue together. You can either use the "Development" menu on the left, or use a "closing keyword" in your description https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-10-01 18:59 UTC, Samuel-Therrien-Beslogic requested changes
Your typing error should be fixed simply by adding the return type annotation on your model methods.

It would be nicer if the default dev DB actually came with various progressions (it can be randomized just like before, but on DB creation instead of every get)
![image](https://github.com/user-attachments/assets/eb9d51c8-a7be-4e13-8abf-e7b9a76305fe)

2024-10-01 18:59 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/models.py
> +        return reduce(lambda x, y: x + y.quantity, batch_species, 0)
A reduce+add is just a sum ;)
```suggestion
        return sum(specie.quantity for specie in batch_species)
```

2024-10-01 18:59 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/models.py
> +        return reduce(lambda x, y: x + y.quantity, site_species, 0)
A reduce+add is just a sum ;)
```suggestion
        return sum(specie.quantity for specie in site_species)
```

2024-10-01 18:59 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/models.py
> +        sponsored_plant_count = reduce(lambda x, y: x + y.plant_count(), batches, 0)
A reduce+add is just a sum ;)
```suggestion
        sponsored_plant_count = sum(batch.plant_count() for specie in batches)
```

2024-10-01 20:04 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/models.py
> +        sponsored_plant_count = sum(batch.plant_count() for specie in batches)
My bad, I mis-copy-pasted
```suggestion
        sponsored_plant_count = sum(batch.plant_count() for batch in batches)
```

2024-10-01 20:05 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/models.py
> +        sponsored_plant_count = sum(batch.plant_count() for specie in batches)
My bad, I mis-copy-pasted
```suggestion
        sponsored_plant_count = sum(batch.plant_count() for batch in batches)
```

2024-10-01 20:07 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/management/commands/initialize_database.py
> +        survived_count = random.randint(100, 200)
example
```suggestion
        survived_count = random.randint(100, 300)
```

2024-10-01 20:12 UTC, Samuel-Therrien-Beslogic commented on canopeum_backend/canopeum_backend/models.py
> +    def plant_count(self):
```suggestion
    def plant_count(self) -> int:
```

2024-10-01 20:20 UTC, NicolasDontigny commented
> Your typing error should be fixed simply by adding the return type annotation on your model methods.
> 
> It would be nicer if the default dev DB actually came with various progressions (it can be randomized just like before, but on DB creation instead of every get) ![image](https://private-user-images.githubusercontent.com/84519004/372612663-eb9d51c8-a7be-4e13-8abf-e7b9a76305fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MTI1MjksIm5iZiI6MTcyNzgxMjIyOSwicGF0aCI6Ii84NDUxOTAwNC8zNzI2MTI2NjMtZWI5ZDUxYzgtYTdiZS00ZTEzLThhYmYtZTdiOWE3NjMwNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE5NTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2YzMDZkNDg4MDViNWY2ZGVjYzlkZDU4OTBiMzY3ZTQ0YzU2ZmQyNzg1MGJkZDRkM2JlMDI2ZThjMmJhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EcHbkE0Q746A_c84IuE3JblIwYgi_bd5NgGDeDUA5kc)

Added type annotations

2024-10-03 23:14 UTC, Samuel-Therrien-Beslogic approved these changes

2024-10-03 23:14 UTC, merged